/*
 * Netbeans 8.0 
 * JDK 1.7  
 */

package sistem.pakar.view;

import sistem.pakar.FrameMain;

/**
 *
 * @author casper
 */
public class PanelBantuan extends javax.swing.JPanel {

    /**
     * Creates new form PanelBantuan
     */
    public PanelBantuan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iPanelBorder1 = new sistem.pakar.component.IPanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CARA MENGGUNAKAN SISTEM");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("<html>\n<div style=\"height: 3cm;\">\n<ol>\n<li>AKSES MENU DIAGNOSA</li><br>\n<li>INPUT GEJALA  YANG DIDERITA ANAK</li>\n<li>PILIH TOMBOL PROSES</li>\n<li>MASUKKAN NILAI INTENSITAS GEJALA : </li>\n<ul><li>JARANG [0 – 5]</li>\n<li>SEDANG [2 – 8]</li>\n<li>SERING [5 – 10] </li> </ul>\n<li>PILIH TOMBOL PROSES UNTUK MENAMPILAKN HASIL DIAGNOSA</li>\n<li>HASIL DIAGNOSA BERUPA HARDPRINT DAPAT DIAKSES DENGAN MEMILIH TOMBOL PRINT</li>\n<li>SEBELUM MELIHAT LAPORAN HASIL  DIAGNOSA, ANDA WAJIB MENGISI DATA PRIBADI DAN DATA ANAK.</li>\n<li>SETELAH LAPORAN HASIL DIAGNOSA TAMPIL, ANDA DAPAT MEMILIH TOMBOL SAVE UNTUK MENYIMPAN DATA ATAU PRINT UNTUK MENCETAK. TOMBOL TERSEBUT TERLETAK PADA SEBELAH KANAN ATAS LAPORAN.\n</li>\n</ol>\n</div>\n</html>\n");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout iPanelBorder1Layout = new javax.swing.GroupLayout(iPanelBorder1);
        iPanelBorder1.setLayout(iPanelBorder1Layout);
        iPanelBorder1Layout.setHorizontalGroup(
            iPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iPanelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(iPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        iPanelBorder1Layout.setVerticalGroup(
            iPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iPanelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(iPanelBorder1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sistem.pakar.component.IPanelBorder iPanelBorder1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    // End of variables declaration//GEN-END:variables
}
