/*
 * Netbeans 8.0 
 * JDK 1.7  
 */
package sistem.pakar.view;

import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import sistem.pakar.component.TableModelDerajatKeanggotaan;
import swingx.component.table.renderer.TableCellColorAlignmentRenderer;
import swingx.component.table.renderer.TableCellColorRenderer;

/**
 *
 * @author casper
 */
public class PanelFuzzyfikasi extends javax.swing.JPanel {

    /**
     * Creates new form PanelFuzzyfikasi
     */
    private FrameMain frameMain;
    private PanelDiagnosa panelDiagnosa;
    private TableModelDerajatKeanggotaan tableModel;

    public PanelFuzzyfikasi(FrameMain frameMain, PanelDiagnosa panelDiagnosa) {
        initComponents();
        this.frameMain = frameMain;
        this.panelDiagnosa = panelDiagnosa;

        tableModel = new TableModelDerajatKeanggotaan();

    }

    public void setData() {
        tableModel.setList(frameMain.getRule().getListKeanggotaans());
        JTable table = new JTable(tableModel) {
            protected JTableHeader createDefaultTableHeader() {
                return new GroupableTableHeader(columnModel);
            }
        };

        TableColumnModel cm = table.getColumnModel();
        ColumnGroup columnGroup = new ColumnGroup("Derajat Keanggotaan (µ)");
        columnGroup.add(cm.getColumn(1));
        columnGroup.add(cm.getColumn(2));
        columnGroup.add(cm.getColumn(3));

        GroupableTableHeader header = (GroupableTableHeader) table.getTableHeader();
        header.addColumnGroup(columnGroup);
        jScrollPane1.setViewportView(table);

        table.setRowHeight(25);

        new swingx.component.table.renderer.TableColumnSizeRenderer().setRenderSizeColumn(table, JTable.AUTO_RESIZE_OFF);

        table.getColumnModel().getColumn(0).setCellRenderer(new TableCellColorRenderer());
        table.getColumnModel().getColumn(1).setCellRenderer(new TableCellColorAlignmentRenderer(JLabel.CENTER));
        table.getColumnModel().getColumn(2).setCellRenderer(new TableCellColorAlignmentRenderer(JLabel.CENTER));
        table.getColumnModel().getColumn(3).setCellRenderer(new TableCellColorAlignmentRenderer(JLabel.CENTER));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
