/*
 * Netbeans 8.0 
 * JDK 1.7  
 */
package sistem.pakar.view;

import sistem.pakar.FrameMain;

/**
 *
 * @author casper
 */
public class PanelMenuUtama extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuUtama
     */
    private final FrameMain frameMain;

    public PanelMenuUtama(FrameMain frameMain) {
        initComponents();
        this.frameMain = frameMain;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonDiagnosa = new javax.swing.JButton();
        buttonPerilaku = new javax.swing.JButton();
        buttonBantuan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        buttonDiagnosa.setText("Diagnosa");
        buttonDiagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDiagnosaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonDiagnosa);
        buttonDiagnosa.setBounds(40, 190, 150, 30);

        buttonPerilaku.setBackground(new java.awt.Color(255, 255, 255));
        buttonPerilaku.setText("Perilaku Abnormal");
        buttonPerilaku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerilakuActionPerformed(evt);
            }
        });
        jPanel1.add(buttonPerilaku);
        buttonPerilaku.setBounds(40, 220, 150, 30);

        buttonBantuan.setText("Bantuan");
        buttonBantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBantuanActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBantuan);
        buttonBantuan.setBounds(40, 250, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/Untitled-1_02.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 0, 280, 330);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/Untitled-1_04.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 300, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/Untitled-1_05.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 90, 300, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDiagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDiagnosaActionPerformed
        frameMain.getPanelDiagnosa().showPanel("card1");
        frameMain.getPanelDiagnosa().showMenu("menu1");
        frameMain.setPanel(frameMain.getPanelDiagnosa());
    }//GEN-LAST:event_buttonDiagnosaActionPerformed

    private void buttonPerilakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerilakuActionPerformed
        frameMain.getPanelDiagnosa().showPanel("card6");
        frameMain.getPanelDiagnosa().showMenu("menu2");
        frameMain.setPanel(frameMain.getPanelDiagnosa());
    }//GEN-LAST:event_buttonPerilakuActionPerformed

    private void buttonBantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBantuanActionPerformed
        frameMain.getPanelDiagnosa().showPanel("card7");
        frameMain.getPanelDiagnosa().showMenu("menu2");
        frameMain.setPanel(frameMain.getPanelDiagnosa());
    }//GEN-LAST:event_buttonBantuanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBantuan;
    private javax.swing.JButton buttonDiagnosa;
    private javax.swing.JButton buttonPerilaku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
