/*
 * Netbeans 8.0 
 * JDK 1.7  
 */
package sistem.pakar.view;

import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JTable;
import swingx.component.table.renderer.TableCellColorAlignmentRenderer;

/**
 *
 * @author casper
 */
public class PanelHasil extends javax.swing.JPanel {

    /**
     * Creates new form PanelHasil
     */
    private PanelDiagnosa panelDiagnosa;
    private FrameMain frameMain;

    public PanelHasil(FrameMain frameMain, PanelDiagnosa panelDiagnosa) {
        initComponents();
        this.frameMain = frameMain;
        this.panelDiagnosa = panelDiagnosa;
        setOpaque(false);
        table.setRowHeight(25);
    }

    public void setHasilDiagnosa(double[] wa) {
        Object[][] object = new Object[5][3];
        object[0][0] = "ADHD";
        object[0][1] = getValue(wa[0]);
        object[0][2] = output(wa[0]);

        object[1][0] = "PERKEMBANGAN BELAJAR";
        object[1][1] = getValue(wa[1]);
        object[1][2] = output(wa[1]);

        object[2][0] = "KETERAMPILAN MOTORIK ";
        object[2][1] = getValue(wa[2]);
        object[2][2] = output(wa[2]);

        object[3][0] = "KOMUNIKASI";
        object[3][1] = getValue(wa[3]);
        object[3][2] = output(wa[3]);

        object[4][0] = "AUTISME";
        object[4][1] = getValue(wa[4]);
        object[4][2] = output(wa[4]);

        table.setModel(new javax.swing.table.DefaultTableModel(
                object,
                new String[]{
                    "Perilaku Abnormal", "Hasil", "Variabel"
                }
        ) {

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        table.getColumnModel().getColumn(0).setPreferredWidth(250);
        table.getColumnModel().getColumn(1).setPreferredWidth(5);
        table.getColumnModel().getColumn(1).setPreferredWidth(10);

        table.getColumnModel().getColumn(0).setCellRenderer(new TableCellColorAlignmentRenderer(JLabel.LEFT));
        table.getColumnModel().getColumn(1).setCellRenderer(new TableCellColorAlignmentRenderer(JLabel.CENTER));
        table.getColumnModel().getColumn(2).setCellRenderer(new TableCellColorAlignmentRenderer(JLabel.CENTER));

        int x = 0;
        for (int i = 0; i < wa.length; i++) {
            for (int j = i; j < wa.length; j++) {
                if (new Double(getValue(wa[x])+"") <= new Double(getValue(wa[j])+"")) {
                    x = j;
                }
            }
        }

        String string = "";
        String string2 = "";
        for (int i = 0; i < wa.length; i++) {
            if (wa[x] == wa[i]) {
                string = string + object[i][0] + " dengan kategori " + object[i][2] + " ; ";

                if (i == 2 || i == 3 || i == 4) {
                    string2 = string2 + " " + Saran.saran[i][0];
                } else {
                    if (object[i][2].equals("RINGAN")) {
                        string2 = string2 + object[i][0]+"\n " + Saran.saran[i][0]+"\n\n\n";
                    } else if (object[i][2].equals("SEDANG")) {
                        string2 = string2 + object[i][0]+"\n " + Saran.saran[i][1]+"\n\n\n";
                    } else if (object[i][2].equals("BERAT")) {
                        string2 = string2 + object[i][0]+"\n " + Saran.saran[i][2]+"\n\n\n";
                    }
                }
            }
        }

        String[] vstring = string.split("; ");
        string = "";
        for (int i = 0; i < vstring.length; i++) {
            if (i == vstring.length - 1) {
                string = string + vstring[i] + " ";
            } else if (i == vstring.length - 2) {
                string = string + vstring[i] + " dan ";
            } else {
                string = string + vstring[i] + ", ";
            }
        }

        jTextArea1.setText("Berdasarkan hasil diagnosa dapat disimpulkan bahwa anak "
                + "memiliki gangguan " + string + "");
        jTextArea2.setText(string2);
    }

    private Object getValue(double x) {
        if ((x + "").equals("NaN")) {
            return 0;
        } else {
            DecimalFormat format = new DecimalFormat("#0.000");
            return format.format(x);
        }
    }

    private String output(double x) {
        if (x > 0 && x <= 3.5) {
            return "RINGAN";
        } else if (x > 3.5 && x <= 6.5) {
            return "SEDANG";
        } else if (x > 6.5 && x <= 10) {
            return "BERAT";
        } else {
            return "";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iPanelBorder1 = new sistem.pakar.component.IPanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        iPanelBorder2 = new sistem.pakar.component.IPanelBorder();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HASIL DIAGNOSA AWAL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PERILAKU ABNORMAL PERKEMBANGAN ANAK");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Hasil Diagnosa Perilaku Abnormal :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("SARAN / TINDAKAN");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(200);
            table.getColumnModel().getColumn(1).setPreferredWidth(25);
        }

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout iPanelBorder1Layout = new javax.swing.GroupLayout(iPanelBorder1);
        iPanelBorder1.setLayout(iPanelBorder1Layout);
        iPanelBorder1Layout.setHorizontalGroup(
            iPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iPanelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(iPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(iPanelBorder1Layout.createSequentialGroup()
                        .addGroup(iPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        iPanelBorder1Layout.setVerticalGroup(
            iPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iPanelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/stock_print.png"))); // NOI18N
        jButton5.setText("Print");
        jButton5.setPreferredSize(new java.awt.Dimension(120, 35));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        iPanelBorder2.add(jButton5);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/process.png"))); // NOI18N
        jButton3.setText("Tampilkan Proses");
        jButton3.setPreferredSize(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        iPanelBorder2.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/undo.png"))); // NOI18N
        jButton4.setText("Batal");
        jButton4.setPreferredSize(new java.awt.Dimension(120, 35));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        iPanelBorder2.add(jButton4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iPanelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(iPanelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iPanelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iPanelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        panelDiagnosa.showPanel("card3");
        panelDiagnosa.showMenu("menu3");
        panelDiagnosa.getPanelNilaiDerajatKeanggotaan().setData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        frameMain.setPanel(new PanelMain(frameMain));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        panelDiagnosa.showPanel("card7");
        panelDiagnosa.showMenu("menu3");
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sistem.pakar.component.IPanelBorder iPanelBorder1;
    private sistem.pakar.component.IPanelBorder iPanelBorder2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    public String getHasilDiagnosa() {
        return jTextArea1.getText();
    }

    public String getSaran() {
        return jTextArea2.getText();
    }

    public JTable getTable() {
        return table;
    }

}
