/*
 * Netbeans 8.0 
 * JDK 1.7  
 */
package sistem.pakar.view;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTabbedPane;
import sistem.pakar.sugeno.WeightAverage;

/**
 *
 * @author casper
 */
public class PanelDiagnosa extends javax.swing.JPanel {

    /**
     * Creates new form PanelDiagnosa
     */
    private FrameMain frameMain;
    private PanelNilaiIntesitas panelNilaiIntesitas;
    private PanelGejala panelGejala;
    private PanelFuzzyfikasi panelFuzzyfikazi;
    private PanelInferensi panelInferensi;
    private PanelDeffuzyfikasi panelDeffuzyfikasi;

    private PanelPredikatAturan panelPredikatAturan;
    private PanelHasil panelHasil;
    private PanelPerilaku panelPerilaku;
    private PanelPasien panelPasien;
    private PanelBantuan panelBantuan;
    private PanelAdmin panelAdmin;

    List<WeightAverage> listRule;

    public PanelDiagnosa(FrameMain frameMain) {
        initComponents();
        this.frameMain = frameMain;

        tabbedPane = new JTabbedPane();

        listRule = new ArrayList<>();

        panelGejala = new PanelGejala(frameMain, this);
        panelNilaiIntesitas = new PanelNilaiIntesitas(frameMain, this);
        panelFuzzyfikazi = new PanelFuzzyfikasi(frameMain, this);
        panelInferensi = new PanelInferensi(frameMain, this);
        panelDeffuzyfikasi = new PanelDeffuzyfikasi(frameMain, this);
        panelHasil = new PanelHasil(frameMain, this);
        
        panelPredikatAturan = new PanelPredikatAturan(frameMain, this);
        panelPerilaku = new PanelPerilaku(frameMain);
        panelPasien = new PanelPasien(frameMain, this);
        panelBantuan = new PanelBantuan(frameMain, this);
        panelAdmin = new PanelAdmin(frameMain);

        panelNilaiIntesitas.setOpaque(false);
        panelGejala.setOpaque(false);
        panelFuzzyfikazi.setOpaque(false);
        panelPredikatAturan.setOpaque(false);
        panelHasil.setOpaque(false);
        panelPerilaku.setOpaque(false);
        panelPasien.setOpaque(false);
        panelBantuan.setOpaque(false);
        panelInferensi.setOpaque(false);
        panelAdmin.setOpaque(false);

        tabbedPane.addTab("TABEL FUZZYFIKASI", panelFuzzyfikazi);
        tabbedPane.addTab("TABEL INFERENSI", panelInferensi);
        tabbedPane.addTab("TABEL DEFFUZIKAZY", panelDeffuzyfikasi);

        tabbedPane.setOpaque(false);

        jPanel3.add(panelGejala, "card1");
        jPanel3.add(panelNilaiIntesitas, "card2");
        jPanel3.add(tabbedPane, "card3");
        jPanel3.add(panelHasil, "card4");
        jPanel3.add(panelPasien, "card5");
        jPanel3.add(panelPerilaku, "card6");
        jPanel3.add(panelBantuan, "card7");
        jPanel3.add(panelAdmin, "card8");
        
//        iPanel1.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/BACKGROUNG1.jpg"))); // NOI18N

    }

    public void showPanel(String panel) {
        ((CardLayout) jPanel3.getLayout()).show(jPanel3, panel);
    }

    public void showMenu(String panel) {
        ((CardLayout) panelMenu.getLayout()).show(panelMenu, panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iPanel1 = new sistem.pakar.component.IPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        buttonMenuUtama = new sistem.pakar.component.IButton();
        buttonAdmin = new sistem.pakar.component.IButton();
        jPanel2 = new javax.swing.JPanel();
        buttonMenuUtama1 = new sistem.pakar.component.IButton();
        jPanel4 = new javax.swing.JPanel();
        buttonMenuUtama2 = new sistem.pakar.component.IButton();
        jPanel5 = new javax.swing.JPanel();
        buttonMenuUtama3 = new sistem.pakar.component.IButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("MENU");

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.CardLayout());

        panelMenu.setOpaque(false);
        panelMenu.setLayout(new java.awt.CardLayout());

        jPanel1.setOpaque(false);

        buttonMenuUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/home-1.png"))); // NOI18N
        buttonMenuUtama.setText("Menu Utama");
        buttonMenuUtama.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonMenuUtama.setPreferredSize(new java.awt.Dimension(173, 41));
        buttonMenuUtama.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/home-2.png"))); // NOI18N
        buttonMenuUtama.setRoundRect(true);
        buttonMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuUtamaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonMenuUtama);

        buttonAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/admin.png"))); // NOI18N
        buttonAdmin.setText("Data Admin");
        buttonAdmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonAdmin.setPreferredSize(new java.awt.Dimension(173, 41));
        buttonAdmin.setRoundRect(true);
        buttonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdminActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAdmin);

        panelMenu.add(jPanel1, "menu1");

        jPanel2.setOpaque(false);

        buttonMenuUtama1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/back-1.png"))); // NOI18N
        buttonMenuUtama1.setText("Kembali");
        buttonMenuUtama1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonMenuUtama1.setPreferredSize(new java.awt.Dimension(173, 41));
        buttonMenuUtama1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/back-2.png"))); // NOI18N
        buttonMenuUtama1.setRoundRect(true);
        buttonMenuUtama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuUtama1ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonMenuUtama1);

        panelMenu.add(jPanel2, "menu2");

        jPanel4.setOpaque(false);

        buttonMenuUtama2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/home-1.png"))); // NOI18N
        buttonMenuUtama2.setText("Menu Utama");
        buttonMenuUtama2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonMenuUtama2.setPreferredSize(new java.awt.Dimension(173, 41));
        buttonMenuUtama2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/home-2.png"))); // NOI18N
        buttonMenuUtama2.setRoundRect(true);
        buttonMenuUtama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuUtama2ActionPerformed(evt);
            }
        });
        jPanel4.add(buttonMenuUtama2);

        panelMenu.add(jPanel4, "menu3");

        jPanel5.setOpaque(false);

        buttonMenuUtama3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/back-1.png"))); // NOI18N
        buttonMenuUtama3.setText("Kembali");
        buttonMenuUtama3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonMenuUtama3.setPreferredSize(new java.awt.Dimension(173, 41));
        buttonMenuUtama3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/sistem/pakar/resources/back-2.png"))); // NOI18N
        buttonMenuUtama3.setRoundRect(true);
        buttonMenuUtama3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuUtama3ActionPerformed(evt);
            }
        });
        jPanel5.add(buttonMenuUtama3);

        panelMenu.add(jPanel5, "menu4");

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><center>SISTEM PAKAR<br>\nDIAGNOSA PERILAKU ABNORMAL PERKEMBANGAN ANAK</center></html>");

        javax.swing.GroupLayout iPanel1Layout = new javax.swing.GroupLayout(iPanel1);
        iPanel1.setLayout(iPanel1Layout);
        iPanel1Layout.setHorizontalGroup(
            iPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(iPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(iPanel1Layout.createSequentialGroup()
                        .addGroup(iPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iPanel1Layout.createSequentialGroup()
                        .addGroup(iPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addGap(10, 10, 10))))
        );
        iPanel1Layout.setVerticalGroup(
            iPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(iPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(iPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 274, Short.MAX_VALUE))
                    .addGroup(iPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        add(iPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuUtamaActionPerformed
        frameMain.setPanel(new PanelMain(frameMain));
    }//GEN-LAST:event_buttonMenuUtamaActionPerformed

    private void buttonMenuUtama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuUtama1ActionPerformed
       frameMain.setPanel(new PanelMain(frameMain));
    }//GEN-LAST:event_buttonMenuUtama1ActionPerformed

    private void buttonMenuUtama2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuUtama2ActionPerformed
        buttonMenuUtama1ActionPerformed(evt);
    }//GEN-LAST:event_buttonMenuUtama2ActionPerformed

    private void buttonMenuUtama3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuUtama3ActionPerformed
        showPanel("card4");
        showMenu("menu3");
    }//GEN-LAST:event_buttonMenuUtama3ActionPerformed

    private void buttonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdminActionPerformed
        panelAdmin.setData();
        showPanel("card8");
        showMenu("menu3");
    }//GEN-LAST:event_buttonAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sistem.pakar.component.IButton buttonAdmin;
    private sistem.pakar.component.IButton buttonMenuUtama;
    private sistem.pakar.component.IButton buttonMenuUtama1;
    private sistem.pakar.component.IButton buttonMenuUtama2;
    private sistem.pakar.component.IButton buttonMenuUtama3;
    private sistem.pakar.component.IPanel iPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
    private JTabbedPane tabbedPane;

    public PanelNilaiIntesitas getPanelNilaiIntesitas() {
        return panelNilaiIntesitas;
    }

    public PanelGejala getPanelGejala() {
        return panelGejala;
    }

    public PanelFuzzyfikasi getPanelFuzzyfikazi() {
        return panelFuzzyfikazi;
    }

    public PanelPredikatAturan getPanelPredikatAturan() {
        return panelPredikatAturan;
    }

    public PanelHasil getPanelHasil() {
        return panelHasil;
    }

    public List<WeightAverage> getListRule() {
        return listRule;
    }

    public void setListRule(List<WeightAverage> listRule) {
        this.listRule = listRule;
    }

    public PanelInferensi getPanelInferensi() {
        return panelInferensi;
    }

    public PanelDeffuzyfikasi getPanelDeffuzyfikasi() {
        return panelDeffuzyfikasi;
    }

}
